;﻿;﻿D3 区：CS、A0、A1 —— A3 区：CS1、A0、A1
;D3 区：PC0、PC1 —— F5 区：KL1、KL2
;D3 区 ：JP20、B、C —— F5 区：A、B、C
EXTRN InitKeyDisplay:NEAR, Display8:NEAR, GetKey:NEAR
EXTRN F1:BYTE

_STACK SEGMENT STACK
DB 100 dup(?)
_STACK ENDS

_DATA SEGMENT WORD PUBLIC 'DATA'
BUFFER DB 0C1H,0A4H,00H,00H
BOUT DB 8 dup(0) ;结果
BUF2 DW 0101H ;整数二进制
BUF2INT DB 5 dup(?) ;整数十进制
BUF3 DB 00H ;指数
BUF4 DW 0000H ;小数
_DATA ENDS

CODE SEGMENT

MAIN PROC NEAR
ASSUME CS:CODE, DS:_DATA,SS:_STACK 
MOV AX,_DATA
MOV DS,AX 
MOV ES,AX
CALL InitKeyDisplay ;对键盘、数码管扫描控制器8255初始化
MOV F1,0 ;清除显示
C1: LEA DI,BUFFER
MOV CX,8 ;按键次数
CALL GetKey ;得到4字节十六进制数
MOV F1,1 ;接收到第一个键，才清除显示
MOV CX,2
MOV DI,3
MOV SI,0
C2: MOV AL,BUFFER[SI]
MOV AH,BUFFER[DI]
XCHG AH,AL
MOV BUFFER[SI],AL
MOV BUFFER[DI],AH
INC SI
DEC DI
LOOP C2
;MOV SI,WORD PTR BUFFER
;MOV DI,WORD PTR BUFFER + 2
;LEA SI,BUFFER
CALL ITOF ;转换
MOV CX,4
MOV DI,7
MOV SI,0
C3: MOV AL,BOUT[SI]
MOV AH,BOUT[DI]
XCHG AH,AL
MOV BOUT[SI],AL
MOV BOUT[DI],AH
INC SI
DEC DI
LOOP C3
LEA SI,BOUT
CALL Display8
JMP C1
MAIN ENDP

ITOF PROC NEAR
LEA BX,BUFFER ;float位置
LEA DI,BOUT ;输出
MOV AH,[BX] ;取前8位
MOV CL,0
MOV [DI],CL
TEST AH,10000000B ;符号位
JZ I1
MOV AH,11H
MOV [DI],AH ;符号记录
I1: MOV AH,[BX] ;从小数取
MOV AL,[BX+1]
SHL AX,1
SUB AH,127 ;IEEE规则减127
MOV BUF3,AH ;取得指数
LEA BX,BUFFER+1
MOV AH,[BX]
MOV AL,[BX+1] ;取出整数部分
OR AX,8000H ;最高位1
CALL MOVE ;取整数部分BUF3位到BUF2（不高于16位），取小数部分到BUF4
CALL RECINT ;至此符号位和整数位已经得到赋值
CALL RECPOINT ;转换小数
MOV AL,BOUT+5
OR AL,10000000B ;小数点
MOV BOUT+5,AL
RET
ITOF ENDP

RECINT PROC NEAR ;转BUF2为10进制,记录整数在3~7位
CALL TRANSINT
MOV SI,1
MOV DI,0
MOV CX,5 ;循环次数
MOV BX,5
R1: MOV DL,BUF2INT[DI]
MOV BOUT[BX],DL
DEC BX
INC DI
LOOP R1
RET
RECINT ENDP

RECPOINT PROC NEAR ;转BUF4为10进制,记录小数在2~1位
MOV AX,BUF4
XOR BX,BX
MOV DH,50H
MOV CX,4
R2: SHL AX,1 ;取一位
PUSHF
POP DI ;取CF
TEST DI,0001H ;检测1
JZ R3
ADD BH,DH ;BCD直接相加
R3: SHR DH,1 ;除以2
LOOP R2
PUSH BX
XOR AX,AX
AND BH,0FH ;取后半部分
MOV AL,BH ;取个位数部分
MOV DL,10
DIV DL ;AL存储除法操作的商，AH存储除法操作的余数
MOV BOUT+7,AH ;最后一位
POP BX
MOV CL,4
SHR BH,CL ;取高位
ADD BH,AL
MOV BOUT+6,BH ;倒数第二位
RET
RECPOINT ENDP

TRANSINT PROC NEAR ;2转10
MOV DX,BUF2
MOV BX,10000 ;除数
MOV CX,5 ;除数的除数
MOV SI,4 ;取余次数
MOV DI,10
T1: MOV AX,DX
MOV DX,0
DIV BX
MOV BUF2INT[SI],AL
PUSH DX
MOV AX,BX
MOV DX,0
DIV DI
MOV BX,AX
POP DX
DEC SI
LOOP T1
RET
TRANSINT ENDP

MOVE PROC NEAR ;取整数部分和小数部分
MOV BL,BUF3
CMP BL,0
JAE A1
NEG BL ;XOR BH,BH; SUB BH,BL
DEC BL ;小数点已经在第一位
MOV CL,BL
SHR AX,CL ;移动小数点
MOV BUF4,AX ;保存在BUF4
MOV AX,0
MOV BUF2,AX ;整数部分0
JMP A2
A1: INC BL ;小数点已经在第一位
MOV BH,16
SUB BH,BL
CMP BH,0
JB A2 ;小于0，即整数超过16位
PUSH AX
MOV CL,BH
SHR AX,CL ;小数点右移，左侧位整数部分
MOV BUF2,AX ;取出整数
POP AX
MOV CL,BL
SHL AX,CL ;剩下BH个小数位
MOV BUF4,AX
A2: RET
MOVE ENDP

CODE ENDS
END MAIN
